// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdhygfawaobokhmlvczf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkaHlnZmF3YW9ib2tobWx2Y3pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5NjM1MjEsImV4cCI6MjA1NTUzOTUyMX0.-EylqDeb3jWcdq-SSfn8PB0C0m_nF8_OQB_pKypoGWc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);